export enum Path {
  DEFAULT = '/',
  LOGIN = '/login',
  REQUEST_CREATE = '/requests/create',
  REQUESTS = '/requests',
  REQUEST_CARD = '/requests/:id',
  RESOURCES = '/resources',
  RESOURCE_TYPE_CREATE = '/resource-types/create',
  RESOURCE_TYPE_UPDATE = '/resource-types/:id',
  RESOURCE_TYPES = '/resource-types',
  RESOURCE_POOL_CHART = '/resource-pools/chart',
  RESOURCE_POOL_CREATE = '/resource-pools/create',
  RESOURCE_POOL_UPDATE = '/resource-pools/:id',
  RESOURCE_POOLS = '/resource-pools',
  EMPLOYEE_CARD = '/employees/:id',
  EMPLOYEES = '/employees',
  SETTINGS = '/settings',
}
